package API_RESPONSE_AUTOGENERATED_FINDBYT_F_CONSTANTS_RR6_PROJ_GEN_MAIN_FILE_NUMB238_MODG3_DBG1_TYPEFILE_CONSTANT

import NETWORK_WEB_THREE_POINT_ZERO_API_UTILITIES_TYPE_STRUCTURES "main/API/response-structure"

const (
	WHOIS_API_URL_WHOIS     = "https://www.whoisxmlapi.com/whoisserver/WhoisService?domainName=%s&username=%s&password=%s&outputFormat=JSON"
	API_LAYER_URL_BIN_CHECK = "https://api.apilayer.com/bincheck/%s"
	API_LAYER_PHONE_CHECK   = "http://apilayer.net/api/validate?access_key=%s&number=%s&country_code=&format=1"
	//cd3af5f7d1897dc1707c47d05c3759fd

)

var (
	Struct1 = NETWORK_WEB_THREE_POINT_ZERO_API_UTILITIES_TYPE_STRUCTURES.WHOIS_XML_API_RESPONSE_STRUCT1_MODG3{}
)

var (
	WHOIS_UPDATED_DATE                                                            = Struct1.WhoisRecord.UpdatedDate
	WHOIS_CONTACT_EMAIL                                                           = Struct1.WhoisRecord.ContactEmail
	WHOIS_ADMIN_ORGANIZATION_NAME                                                 = Struct1.WhoisRecord.AdministrativeContact.Organization
	WHOIS_ADMIN_COUNTRY_NAME                                                      = Struct1.WhoisRecord.AdministrativeContact.Country
	WHOIS_REGISTRANT_COUNTRY_NAME                                                 = Struct1.WhoisRecord.Registrant.Country
	WHOIS_REGISTRANT_COUNTRY_CODE                                                 = Struct1.WhoisRecord.Registrant.CountryCode
	WHOIS_REGISTRANT_COUNTRY_STATE_CODE                                           = Struct1.WhoisRecord.Registrant.State
	WHOIS_REGISTRANT_ORGANIZATION_NAME                                            = Struct1.WhoisRecord.Registrant.Organization
	WHOIS_TECHNICAL_CONTACT_COUNTRY                                               = Struct1.WhoisRecord.TechnicalContact.Country
	WHOIS_TECHNICAL_CONTACT_ORGANIZATION                                          = Struct1.WhoisRecord.TechnicalContact.Organization
	WHOIS_TECHNICAL_CONTACT_STATE_NAME_CODE                                       = Struct1.WhoisRecord.TechnicalContact.State
	WHOIS_RECORD_CREATED_DATE_                                                    = Struct1.WhoisRecord.CreatedDate
	WHOIS_RECORD_CREATED_DATE_NORMALIZED_BY_RECORD                                = Struct1.WhoisRecord.CreatedDateNormalized
	WHOIS_RECORD_CREATED_DATE_MIXED_AUDIT_CREATE_DATE                             = Struct1.WhoisRecord.Audit.CreatedDate
	WHOIS_RECORD_CREATED_DATE_MIXED_AUDIT_UPDATE_DATE                             = Struct1.WhoisRecord.Audit.UpdatedDate
	WHOIS_RECORD_DOMAIN_NAME_EXPIRES_WHEN_DATE                                    = Struct1.WhoisRecord.ExpiresDate
	WHOIS_RECORD_DOMAIN_NAME_EXPIRES_WHEN_DATE_NORMAL                             = Struct1.WhoisRecord.ExpiresDateNormalized
	WHOIS_DOMAIN_NAME_BASED_LAST_RECORDED_STATUS_AND_CHECK                        = Struct1.WhoisRecord.Status
	WHOIS_DOMAIN_NAME_BASED_LAST_RAW_TEXT                                         = Struct1.WhoisRecord.RawText
	WHOIS_DOMAIN_NAME_PARSING_CODE_LAST_RECORDED                                  = Struct1.WhoisRecord.ParseCode
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_HEADER_LAST_RECORDED                           = Struct1.WhoisRecord.Header
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_STRIPPED_WHOIS_TEXT                            = Struct1.WhoisRecord.StrippedText
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_FOOTER                                         = Struct1.WhoisRecord.Footer
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_AUDIT_CREATED_LAST_RECORDED_DATE               = Struct1.WhoisRecord.Audit.CreatedDate
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_AUDIT_UPDATED_LAST_RECORDED_DATE               = Struct1.WhoisRecord.Audit.UpdatedDate
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRAR_NAME                                 = Struct1.WhoisRecord.RegistrarName
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRAR_IANAID                               = Struct1.WhoisRecord.RegistrarIANAID
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRAR_DATE_NORMALIZED                      = Struct1.WhoisRecord.CreatedDateNormalized
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRAR_UPDATED_DATE_NORMALIZED              = Struct1.WhoisRecord.UpdatedDateNormalized
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRAR_EXPIRES_DATE_NORMALIZED              = Struct1.WhoisRecord.ExpiresDateNormalized
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATE_DOMAIN_NAME                      = Struct1.WhoisRecord.RegistryData.DomainName
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_STATUS             = Struct1.WhoisRecord.RegistryData.Status
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_PARSE_CODE         = Struct1.WhoisRecord.RegistryData.ParseCode
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_HEADER             = Struct1.WhoisRecord.RegistryData.Header
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_FOOTER             = Struct1.WhoisRecord.RegistryData.Footer
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_AUDIT              = Struct1.WhoisRecord.RegistryData.Audit
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_CREATED_WHEN       = Struct1.WhoisRecord.RegistryData.Audit.CreatedDate
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_UPDATED_DATE       = Struct1.WhoisRecord.RegistryData.Audit.UpdatedDate
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_REGISTRAR_NAME     = Struct1.WhoisRecord.RegistryData.RegistrarName
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_RegistrarIANAID    = Struct1.WhoisRecord.RegistryData.RegistrarIANAID
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_CREATED_NORMALIZED = Struct1.WhoisRecord.RegistryData.CreatedDateNormalized
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_UPDATED_NORMALIZED = Struct1.WhoisRecord.RegistryData.UpdatedDateNormalized
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_EXPIRES_NORMALIZED = Struct1.WhoisRecord.RegistryData.ExpiresDateNormalized
	WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_WHOIS_SERVER       = Struct1.WhoisRecord.RegistryData.WhoisServer
)

/*

fmt.Println(colors.GRN, "\n---------------[ Contact and Administration ] ---------------------")
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Contact Email            : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_CONTACT_EMAIL, colors.RET_RED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Admin Organization       : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_ADMIN_ORGANIZATION_NAME, colors.RET_RED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Admin Country Name       : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_ADMIN_COUNTRY_NAME, colors.RET_RED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Registrant Country Code  : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_REGISTRANT_COUNTRY_CODE, colors.RET_RED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Registrant State         : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_REGISTRANT_COUNTRY_STATE_CODE, colors.RET_RED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Registrant Country       : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_REGISTRANT_COUNTRY_NAME, colors.RET_RED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Registrant Organization  : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_REGISTRANT_ORGANIZATION_NAME, colors.RET_RED)
			fmt.Println(colors.GRN, "\n---------------[ Dates, Times, and Registration ] ---------------------")
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Created Date             : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_RECORD_CREATED_DATE_, colors.RET_RED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Created Date normal      : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_RECORD_CREATED_DATE_NORMALIZED_BY_RECORD, colors.RET_RED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Audit Created Date       : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_RECORD_CREATED_DATE_MIXED_AUDIT_CREATE_DATE, colors.RET_RED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Audit Updated Date       : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_RECORD_CREATED_DATE_MIXED_AUDIT_UPDATE_DATE, colors.RET_RED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Expires Date             : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_RECORD_DOMAIN_NAME_EXPIRES_WHEN_DATE, colors.RET_RED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Expires Date normal      : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_RECORD_DOMAIN_NAME_EXPIRES_WHEN_DATE_NORMAL, colors.RET_RED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Updated Date             : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_UPDATED_DATE, colors.RET_RED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Registry Date Create     : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRAR_DATE_NORMALIZED, colors.RET_RED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Registry Update Create   : ", colors.HIGH_BLUE, colors.RET_RED, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_UPDATED_NORMALIZED)
			Print_data(colors.RED, "\033[90m", colors.RED, colors.MAG, "Registry Expires Date    : ", colors.HIGH_BLUE, NETWORK_WEB_THREE_POINT_ZERO_UTILITIES_CONSTANTS.WHOIS_DOMAIN_NAME_WHOIS_RECORD_REGISTRY_DATA_LAST_RECORDED_EXPIRES_NORMALIZED, colors.RET_RED)


*/
