package cloud_types

type Response struct {
	HTTP_CODE string
	URL       string
}

type WEB_APP_FIREWALL_WAF struct {
	IDS_NAME     string
	URL          string
	BLOCKED_MSG  string
	BLOCKED_CODE int
}

var TRIPPED_IDS_CONFIG = []WEB_APP_FIREWALL_WAF{
	{"Cloudflare", "https://www.cloudflare.com/", "you have been blocked", 403},
	{"Akamai", "https://www.akamai.com/", "You don't have permission to access", 403},
	{"F5", "https://www.f5.com/", "The requested URL was rejected. Please consult with your administrator.", 403},
	{"CloudFront", "https://docs.aws.amazon.com/", "Generated by cloudfront (CloudFront)", 403},
	{"Fortiweb", "https://www.fortinet.com/", "", 403},
	{"Imperva", "https://www.imperva.com/", "Request unsuccessful. Incapsula incident ID", 403},
	{"Wordfence", "https://www.wordfence.com/products/", "", 403},
}
